services:
  supplier_app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      # Use the internal DNS name/alias of the API service on the shared Docker network
      - ENDPOINT_URL=http://store-manager:5000/stocks/graphql-query
    volumes:
      - .:/app
    networks:
      - labo03-network

networks:
  labo03-network:
    driver: bridge
    external: true
