name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env for app
        run: |
          cat > .env <<'EOF'
          DB_HOST=mysql
          DB_PORT=3306
          DB_NAME=labo03_db
          DB_USER=labo03
          DB_PASS=labo03
          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_DB=0
          EOF

      - name: Create external Docker network (if missing)
        run: docker network create labo03-network || true

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for MySQL init..."
          sleep 25
          docker compose ps

      - name: Run tests inside app container
        run: docker compose exec -T store_manager pytest -q

      - name: Show service logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color mysql | tail -n 200 || true
          docker compose logs --no-color redis | tail -n 200 || true
          docker compose logs --no-color store_manager | tail -n 200 || true
